"""moved breeding and litters to breeding service

Revision ID: 3fc46fab90a9
Revises: 596e799244e6
Create Date: 2024-12-08 19:31:43.884766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3fc46fab90a9'
down_revision: Union[str, None] = '596e799244e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('animal_litter_id_fkey', 'animal', type_='foreignkey')
    op.drop_column('animal', 'litter_id')
    op.drop_table('litter')
    op.drop_table('breeding')
    # ### end Alembic commands ###

def downgrade() -> None:
    # Removing the breeding and litter table completely so no need for this
    pass
