"""Initial configuration animal, medical_record, event, and breeding

Revision ID: e8a7e1e9d79e
Revises: 
Create Date: 2024-12-08 13:00:45.677529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8a7e1e9d79e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('specie', sa.Enum('LION', 'TIGER', 'SHARK', 'PARROT', 'ELEPHANT', 'MONKEY', 'CAMEL', 'SNAKE', 'PANTHER', 'GOAT', 'BEAR', 'FROG', 'POLARBEAR', 'PENGUIN', 'GIRAFFE', 'LEOPARD', 'OCTOPUS', 'EAGLE', 'LIZARD', 'SEAL', 'ZEBRA', name='specie'), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'HERMAPHRODITE', 'ASEXUAL', name='gender'), nullable=False),
    sa.Column('health', sa.Enum('HEALTHY', 'SICK', 'UNDER_OBSERVATION', 'INJURED', 'RECOVERING', 'DECEASED', name='health'), nullable=False),
    sa.Column('acquisition_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('breeding',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_1_id', sa.UUID(), nullable=False),
    sa.Column('parent_2_id', sa.UUID(), nullable=False),
    sa.Column('offspring_id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['offspring_id'], ['animal.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_1_id'], ['animal.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_2_id'], ['animal.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_1_id', 'parent_2_id', 'offspring_id', name='unique_breeding_combination')
    )
    op.create_table('event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('animal_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('BIRTH', 'TRANSFER', 'DEATH', 'MEDICAL', 'BREEDING', 'FEEDING', 'GENERAL_CARE', name='event_type'), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medical_record',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('animal_id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('vet_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medical_record')
    op.drop_table('event')
    op.drop_table('breeding')
    op.drop_table('animal')
    # ### end Alembic commands ###
