from enum import Enum

class SPECIE(str, Enum):
    LION = "LION"
    TIGER = "TIGER"
    SHARK = "SHARK"
    PARROT = "PARROT"
    ELEPHANT = "ELEPHANT"
    MONKEY = "MONKEY"
    CAMEL = "CAMEL"
    SNAKE = "SNAKE"
    PANTHER = "PANTHER"
    GOAT = "GOAT"
    BEAR = "BEAR"
    FROG = "FROG"
    POLARBEAR = "POLARBEAR"
    PENGUIN = "PENGUIN"
    GIRAFFE = "GIRAFFE"
    LEOPARD = "LEOPARD"
    OCTOPUS = "OCTOPUS"
    EAGLE = "EAGLE"
    LIZARD = "LIZARD"
    SEAL = "SEAL"
    ZEBRA = "ZEBRA"

